services:
  - type: web
    name: path-ai
    env: python
    plan: starter

    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"

      # Optional: set this in Render dashboard if you want
      # - key: OPENAI_API_KEY
      #   sync: false